[package]
name = "nwg-embed-resources"
version = "1.0.0"
authors = ["gdube <gdube.475@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
native-windows-gui = {path = "../../", features=["no-styling", "embed-resource", "list-view", "cursor"]}
native-windows-derive = {path = "../../../native-windows-derive"}

[build-dependencies]
embed-resource = "1.3"

